---
- hosts: node1
  gather_facts: true
  become: true
  tasks:
  - name: creating multiple files
    file:
      path: /home/devops/{{ item }}
      state: directory
      mode: '777'
    with_items:
      - dir1
      - dir2
      - dir3
    tags:
      - shiva
 

