---
- hosts: node1
  gather_facts: true
  become: true
  tasks:
  - name: check the folder
    stat:
      path: /home/devops/file22
    register: file
  - debug:
      msg: "yes the folder is available"
    when: file.stat.exists == true
  - name: create a folder
    file:
      path: /home/devops/file22
      state: touch
    when: file.stat.exists == false
